/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/home/index" |
       "/pages/chatRoom/index" |
       "/pages/homePage/activityDetail" |
       "/pages/homePage/goHiking" |
       "/pages/homePage/index" |
       "/pages/insuranceDetail/index" |
       "/pages/insurancePDF/index" |
       "/pages/joinTeam/index" |
       "/pages/login/index" |
       "/pages/message/index" |
       "/pages/mine/index" |
       "/pages/mine/myAblum" |
       "/pages/mine/myActivity" |
       "/pages/mine/myCollect" |
       "/pages/publish/index" |
       "/pages/search/index" |
       "/pages/settings/index" |
       "/pages/share/detail" |
       "/pages/share/index" |
       "/pages/teamDetail/index" |
       "/pages/userSettings/index" |
       "/pages/withTeam/teamDetail" |
       "/pages-sub/demo/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/home/index" | "/pages/share/index" | "/pages/message/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
